module.exports = [
  'txt'
  'rakefile', 'rantfile', '.irbrc', 'irbrc', '.pryrc', 'pryrc', 'capfile', 'gemfile', 'guardfile', '.guardfile', 'vagrantfile', '.autotest', 'thorfile', 'podfile', '.gitignore', '.env', '.env-example'
  'readme', 'makefile', 'license', 'copying', 'credits', 'notice', 'changelog', 'install', 'configure'
  'rb', 'rbw', 'gemspec', 'builder', 'rxml', 'rjs', 'rake', 'rant', 'ru', 'thor', 'rabl', 'jbuilder'
  'clj'
  'erl'
  'go'
  'groovy'
  'html'
  'haml'
  'erb', 'rhtml'
  'css'
  'java'
  'jsp'
  'j2'
  'js'
  'json'
  'ejs'
  'coffee'
  'less'
  'markdown', 'md'
  'c', 'h'
  'cpp', 'hpp'
  'diff'
  'lua'
  'sql', 'mysql'
  'pl'
  'php'
  'py'
  'scala'
  'scm'
  'scss', 'sass'
  'sh'
  'xml'
  'yml', 'yaml'
]
